In [88]:
import pandas as pd
import numpy as np
import re

Welding_Log_Df = pd.read_excel("./welding_Log_Dataset.xlsx")

# Data Cleaning & EDA

### 1- Welding_Log Dataset

In [89]:
Welding_Log_Df.head()

,ISO_N,REV,LINE_NBR,Zone,Joint_N,LINE_CLASS,Joint_Type,Thickness,Diameter,WPS,...,Fit-Up_Date,VT,Vt_Date,PT,Pt_Date,Paut_Report,Paut_Result,Paut_Date,RT,Rt_Date
0,ZA38180-PCS-AM-B10-101-E10-000-01,NaN,400-AM-B10-101-CD2,ZONE 10,FW-01,CD2,BW,9.53,400,04/24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ZA38180-PCS-AM-B10-101-E10-000-01,0.0,400-AM-B10-101-CD2,ZONE 10,SW-01,CD2,BW,9.53,400,04/24,...,45938,VT-0005,45944,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ZA38180-PCS-AM-B10-101-E10-000-01,0.0,400-AM-B10-101-CD2,ZONE 10,SW-02,CD2,BW,9.53,400,04/24,...,45961,VT-0040,46013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ZA38180-PCS-AM-B10-101-E10-000-01,NaN,400-AM-B10-101-CD2,ZONE 10,SW-03,CD2,BW,9.53,400,04/24,...,46181,VT-102,46181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ZA38180-PCS-AM-B10-101-E10-000-01,NaN,400-AM-B10-101-CD2,ZONE 10,SW-04,CD2,BW,9.53,400,04/24,...,46181,VT-102,46181,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Normalizing the Dataset Columns Names

In [90]:
Welding_Log_Df.columns

Index(['ISO_N', 'REV', 'LINE_NBR ', 'Zone', 'Joint_N', 'LINE_CLASS',
       'Joint_Type', 'Thickness', 'Diameter', 'WPS', 'Base Met ',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_ID_One',
       'Welder_ID_Two', 'fit-up', 'Fit-Up_Date', 'VT', 'Vt_Date', 'PT',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'RT', 'Rt_Date'],
      dtype='str')

In [91]:
Welding_Log_Df.columns = (
    Welding_Log_Df.columns.str.strip().str.replace(" ", "_").str.replace("-", "_").str.title()
)

In [92]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Line_Class',
       'Joint_Type', 'Thickness', 'Diameter', 'Wps', 'Base_Met',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_Id_One',
       'Welder_Id_Two', 'Fit_Up', 'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'Rt', 'Rt_Date'],
      dtype='str')

### Data Standardization
converting data from different formats into a single, 
consistent standard format across The entire dataset.

In [93]:
Df_Clms = [
    "Iso_N",
    "Zone",
    "Joint_N",
    "Joint_Type",
    "Welder_Id_One",
    "Welder_Id_Two",
    "Fit_Up",
    "Vt",
    "Pt",
    "Paut_Report",
    "Paut_Result"
]

for col in Df_Clms:
    Welding_Log_Df[col] = Welding_Log_Df[col].str.strip().str.upper()

### Data Type Conversion

In [94]:
Welding_Log_Df.dtypes

Iso_N                str
Rev              float64
Line_Nbr             str
Zone                 str
Joint_N              str
Line_Class           str
Joint_Type        object
Thickness         object
Diameter          object
Wps                  str
Base_Met             str
Filler_Metal         str
Electrode            str
Process              str
Welding_Date      object
Welder_Id_One        str
Welder_Id_Two        str
Fit_Up               str
Fit_Up_Date       object
Vt                   str
Vt_Date           object
Pt                   str
Pt_Date           object
Paut_Report          str
Paut_Result          str
Paut_Date        float64
Rt               float64
Rt_Date          float64
dtype: object

In [95]:
Welding_Log_Df["Rev"].unique()

array([nan,  0.,  1.])

In [96]:
Welding_Log_Df["Rev"] =  Welding_Log_Df["Rev"].fillna(0)
Welding_Log_Df["Rev"] = Welding_Log_Df["Rev"].astype(int)

In [97]:
Welding_Log_Df[Welding_Log_Df["Joint_Type"] == "BW"].shape

(681, 28)

In [98]:
Welding_Log_Df["Joint_Type"].unique()

array(['BW', 'SW', nan, '9,53', 'FW-9'], dtype=object)

In [99]:
Welding_Log_Df["Joint_Type"] = Welding_Log_Df["Joint_Type"].replace("FW-9", "FW").replace("9,53", "BW").replace(9.5,"BW").fillna("BW")

In [100]:
Welding_Log_Df["Joint_Type"].value_counts(dropna=False)

Joint_Type
BW    2849
SW       2
FW       1
Name: count, dtype: int64

In [101]:
Welding_Log_Df["Rt"] = Welding_Log_Df["Rt"].astype(str)

In [102]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Line_Class',
       'Joint_Type', 'Thickness', 'Diameter', 'Wps', 'Base_Met',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_Id_One',
       'Welder_Id_Two', 'Fit_Up', 'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'Rt', 'Rt_Date'],
      dtype='str')

In [103]:
date_columns = [
    "Welding_Date",
    "Fit_Up_Date",
    "Vt_Date",
    "Pt_Date",
    "Paut_Date",
    "Rt_Date"
]

for col in date_columns:
    Welding_Log_Df[col] = pd.to_numeric(
        Welding_Log_Df[col],
        errors="coerce"
    )

    Welding_Log_Df[col] = pd.to_datetime(
        Welding_Log_Df[col],
        unit="D",
        origin="1899-12-30",
        errors="coerce"
    )

In [104]:
Welding_Log_Df[["Welding_Date", "Fit_Up_Date", "Vt_Date", "Pt_Date", "Paut_Date", "Rt_Date"]]

     Welding_Date Fit_Up_Date    Vt_Date Pt_Date Paut_Date Rt_Date
0             NaT         NaT        NaT     NaT       NaT     NaT
1      2025-10-14  2025-10-08 2025-10-14     NaT       NaT     NaT
2      2025-12-22  2025-10-31 2025-12-22     NaT       NaT     NaT
3      2026-06-08  2026-06-08 2026-06-08     NaT       NaT     NaT
4      2026-06-08  2026-06-08 2026-06-08     NaT       NaT     NaT
...           ...         ...        ...     ...       ...     ...
2847          NaT         NaT        NaT     NaT       NaT     NaT
2848          NaT         NaT        NaT     NaT       NaT     NaT
2849          NaT         NaT        NaT     NaT       NaT     NaT
2850          NaT         NaT        NaT     NaT       NaT     NaT
2851          NaT         NaT        NaT     NaT       NaT     NaT

[2852 rows x 6 columns]

### Feature Selection and Column Pruning

In [105]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Line_Class',
       'Joint_Type', 'Thickness', 'Diameter', 'Wps', 'Base_Met',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_Id_One',
       'Welder_Id_Two', 'Fit_Up', 'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'Rt', 'Rt_Date'],
      dtype='str')

droping unnecessary columns

In [106]:
Welding_Log_Df = Welding_Log_Df.drop(columns=[
    "Line_Class", 
    "Thickness",
    "Diameter",
    "Wps",
    "Base_Met",
    "Filler_Metal",
    "Electrode",
    "Process",
    "Paut_Result"
    ]
)

In [107]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Joint_Type',
       'Welding_Date', 'Welder_Id_One', 'Welder_Id_Two', 'Fit_Up',
       'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt', 'Pt_Date', 'Paut_Report',
       'Paut_Date', 'Rt', 'Rt_Date'],
      dtype='str')

In [108]:
Welding_Log_Df["Welder_Id_One"].unique()

<StringArray>
[    nan,   'W03',   'W07',   'W08',   'W01',  'W-01',   'W16',  'W-05',
   'W04',   'W11',  'W-17',   'W18',   'W05',   'W02',   'W15',   'W06',
   'W19',  'W-03',   'W17',   'W33',   'W90',  'W-08',   'W74',   'W72',
  'W107',  'W-04', 'W-017', 'W-011', 'W-015',   'W25',   'W27',   'W09',
   'W39',  'W-02',  'W-39',  'W-27',  'W-09',  'W-40',   'W12',   'W14',
  'W-25',  'W-12',  'W-18',  'W-14',  'W-21',  'W-22',   'W42',  'W-35',
  'W-33',  'W-32',  'W-34',  'W-28',   'W32',  'W-11',  'W-15',   'W93',
   'W94', 'W-107',  'W-06',  'W-38', 'W-108',  'W-07',  'W-72',  'W-93',
  'W-90',  'W-74', 'W- 32', 'W- 34', 'W- 14',  'W-42',  'W-16',   'W22',
   'W21',   'W91',   'W40',  'W-13',  'W-61',      '']
Length: 78, dtype: str

In [109]:
Welding_Log_Df["Welder_Id_Two"].unique()

<StringArray>
[    nan,      '',  'W-57',  'W-46',  'W-42',   'W32',  'W-25',  'W-09',
  'W-21',   'W16',   'W39',  'W-14', 'W-111',  'W-33',  'W-32',  'W-16',
   'W33',   'W07',   'W02',   'W25',  'W-02',  'W-03',  'W-15',  'W-74',
  'W-27']
Length: 25, dtype: str

In [110]:
def Cleaned_Welder_Id(Val):
    # Checking if the the id is a 'NAN' value or None
    if pd.isna(Val) or Val is None:
        return np.nan
    
    # first we have to delect any extra spaces between
    Clean_Val = re.sub(r"[\s-]", "", str(Val)).upper()
    
    if not Clean_Val:
        return np.nan
    
    # we need to extract the 'W' character first
    digits = Clean_Val.lstrip("W")
    
    if len(digits) >= 3 and digits.startswith("0"):
        digits = digits[1:]
    
    if len(digits) == 1 :
        digits = digits.zfill(2)
        
    return f"W{digits}"

Welders_Ids = [
    "Welder_Id_One",
    "Welder_Id_Two",
]


for i in Welders_Ids:
    Welding_Log_Df[i] = Welding_Log_Df[i].apply(Cleaned_Welder_Id)

In [111]:
Welding_Log_Df["Welder_Id_One"].unique()

<StringArray>
[   nan,  'W03',  'W07',  'W08',  'W01',  'W16',  'W05',  'W04',  'W11',
  'W17',  'W18',  'W02',  'W15',  'W06',  'W19',  'W33',  'W90',  'W74',
  'W72', 'W107',  'W25',  'W27',  'W09',  'W39',  'W40',  'W12',  'W14',
  'W21',  'W22',  'W42',  'W35',  'W32',  'W34',  'W28',  'W93',  'W94',
  'W38', 'W108',  'W91',  'W13',  'W61']
Length: 41, dtype: str

### Handling the missing values and duplicates
The dataset contains rows that appear duplicated.

After reviewing them with domain knowledge from the welding process, these records were intentionally retained because they represent welds that had not yet progressed through the execution stages. At the time of data extraction, operational fields such as Welding_Date, Welder_ID_One, Welder_ID_Two, ... were still empty, causing multiple records to appear identical

In [112]:
Welding_Log_Df[Welding_Log_Df.duplicated(keep=False)]

,Iso_N,Rev,Line_Nbr,Zone,Joint_N,Joint_Type,Welding_Date,Welder_Id_One,Welder_Id_Two,Fit_Up,Fit_Up_Date,Vt,Vt_Date,Pt,Pt_Date,Paut_Report,Paut_Date,Rt,Rt_Date
91,ZA38180-PCS-AM-B10-404-E10-000-05,0,400-AM-B10-404-CD2,ZONE 10,FW-05,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
92,ZA38180-PCS-AM-B10-404-E10-000-05,0,400-AM-B10-404-CD2,ZONE 10,FW-05,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
131,ZA38180-PCS-AM-B10-404-E10-000-14,0,400-AM-B10-404-CD2,ZONE 10,FW-02,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
132,ZA38180-PCS-AM-B10-404-E10-000-14,0,400-AM-B10-404-CD2,ZONE 10,FW-02,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
289,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,FW-01,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
291,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,SW-02A,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
293,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,SW-03,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
294,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,FW-04,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
296,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,SW-06,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
329,ZA38180-PCS-AM-B10-502-E10-000-15,0,400-AM-B10-502-CD2,ZONE 10,FW-03,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
330,ZA38180-PCS-AM-B10-502-E10-000-15,0,400-AM-B10-502-CD2,ZONE 10,FW-03,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
397,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,FW-01,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
398,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,SW-02A,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
400,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,SW-03,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
401,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,FW-04,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
402,ZA38180-PCS-AM-B10-501-E10-000-01,0,400-AM-B10-501-CD2,ZONE 10,SW-06,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
2587,ZA38180-PCS-E10-PI-DGA-0043,0,400-AM-B10-502-CD2,ZONE 9,FW-122,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT
2588,ZA38180-PCS-E10-PI-DGA-0043,0,400-AM-B10-502-CD2,ZONE 9,FW-122,BW,NaT,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT

For joints where the welding process has not been performed yet (Welding_Date is null), all test results (PT,Fit_Up, VT, and PAUT) default to 'Pending'.

In [113]:
Test_Clms = [
    "Fit_Up",
    "Vt",
    "Pt",
    "Rt",
    "Paut_Report"
]


for clm in Test_Clms:
    Welding_Log_Df.loc[Welding_Log_Df["Welding_Date"].isnull(),clm] = "PENDING"
    
# We check if we have the report of each Test after the Welding if not we give a value of "NO REPORT"    
for clm in Test_Clms:
    Welding_Log_Df.loc[Welding_Log_Df[clm].isnull(), clm] = "NO REPORT"

### Standardizing Inspection Results
we generated standardized inspection result status columns (`Fit_Up_Result`, `Vt_Result`, `Pt_Result`, `Paut_Result`, `Rt_Result`) based on raw status entries while preserving the original columns:

* **`REJECTED`**: Assigned to joints marked as `"NO REPORT"`.
* **`Pending`**: Maintained for joints where welding/testing has not occurred yet.
* **`ACCEPTED`**: Default classification assigned to all successfully passed inspection records.

In [117]:

mapping = {
    "Fit_Up": "Fit_Up_Result",
    "Vt": "Vt_Result",
    "Pt": "Pt_Result",
    "Paut_Report": "Paut_Result",
    "Rt" : "Rt_Result",
}

for Test_col, Result_col in mapping.items():
    conditions = [
        Welding_Log_Df[Test_col] == "NO REPORT",
        Welding_Log_Df[Test_col] == "PENDING",
    ]
    choices = ["REJECTED", "PENDING"]

    Welding_Log_Df[Result_col] = np.select(
        conditions, choices, default="ACCEPTED"
    )

In [118]:
Welding_Log_Df[~Welding_Log_Df["Welding_Date"].isnull()]

,Iso_N,Rev,Line_Nbr,Zone,Joint_N,Joint_Type,Welding_Date,Welder_Id_One,Welder_Id_Two,Fit_Up,...,Pt_Date,Paut_Report,Paut_Date,Rt,Rt_Date,Fit_Up_Result,Vt_Result,Pt_Result,Paut_Result,Rt_Result
1,ZA38180-PCS-AM-B10-101-E10-000-01,0,400-AM-B10-101-CD2,ZONE 10,SW-01,BW,2025-10-14,W03,NaN,VT-0005,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
2,ZA38180-PCS-AM-B10-101-E10-000-01,0,400-AM-B10-101-CD2,ZONE 10,SW-02,BW,2025-12-22,W03,NaN,VT-0040,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
3,ZA38180-PCS-AM-B10-101-E10-000-01,0,400-AM-B10-101-CD2,ZONE 10,SW-03,BW,2026-06-08,W07,NaN,VT-102,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
4,ZA38180-PCS-AM-B10-101-E10-000-01,0,400-AM-B10-101-CD2,ZONE 10,SW-04,BW,2026-06-08,W07,NaN,VT-102,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
5,ZA38180-PCS-AM-B10-101-E10-000-01,0,400-AM-B10-101-CD2,ZONE 10,SW-05,BW,2026-06-08,W07,NaN,VT-102,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2826,ZA38180-PCS-E10-PI-DGA-0037,0,400-AM-B10-501-CD2,ZONE 8,FW-17,BW,2026-04-20,W16,NaN,VT-0097,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
2827,ZA38180-PCS-E10-PI-DGA-0037,0,400-AM-B10-501-CD2,ZONE 8,FW-18,BW,2026-04-22,W11,NaN,VT-0098,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
2828,ZA38180-PCS-E10-PI-DGA-0037,0,400-AM-B10-501-CD2,ZONE 8,SW-19,BW,2026-04-22,W04,NaN,VT-0098,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
2829,ZA38180-PCS-E10-PI-DGA-0037,0,400-AM-B10-501-CD2,ZONE 8,FW-20,BW,2026-04-22,W11,NaN,VT-0098,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED
2830,ZA38180-PCS-E10-PI-DGA-0037,0,400-AM-B10-501-CD2,ZONE 8,SW-21,BW,2026-04-22,W07,NaN,VT-0098,...,NaT,NO REPORT,NaT,NO REPORT,NaT,ACCEPTED,ACCEPTED,REJECTED,REJECTED,REJECTED

In [149]:
Welding_Log_Df["Joint_N"].value_counts(dropna=False)

Joint_N
FW-01      73
SW-02      49
SW-06      45
FW-03      45
FW-02      43
           ..
SW-90       1
FW-170A     1
FW-203      1
FW-23-A     1
FW-161A     1
Name: count, Length: 442, dtype: int64

In [185]:
Welded = Welding_Log_Df[~Welding_Log_Df["Welding_Date"].isnull()]

### Primary Key Generation (`Weld_Id`)

Because `Joint_N` is non-unique across different Isometric drawings (`Iso_N`), we created a composite primary key **`Weld_Id`** by concatenating `Iso_N` and `Joint_N` (`Iso_N_Joint_N`).

In [182]:
Welding_Log_Df["Weld_Id"] = (
    Welding_Log_Df["Iso_N"].astype(str)
    + "_"
    + Welding_Log_Df["Joint_N"].astype(str)
)

In [183]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Joint_Type',
       'Welding_Date', 'Welder_Id_One', 'Welder_Id_Two', 'Fit_Up',
       'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt', 'Pt_Date', 'Paut_Report',
       'Paut_Date', 'Rt', 'Rt_Date', 'Fit_Up_Result', 'Vt_Result', 'Pt_Result',
       'Paut_Result', 'Rt_Result', 'Weld_Id'],
      dtype='str')